# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
name: saucectl release

on:
  create:
    tags:
      - v*

env:
  GH_TOKEN: ${{secrets.GH_TOKEN}}

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Unshallow
        run: |
          git fetch --prune --unshallow
      -
        name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.14.x
      -
        name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v1
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      -
        name: Trigger node-saucectl release
        run: |
          echo "Release saucectl $(git describe --abbrev | cut -c2-)"
          curl -X POST https://api.github.com/repos/saucelabs/node-saucectl/dispatches \
          -H 'Accept: application/vnd.github.everest-preview+json' \
          -u devx-sauce-bot:$GH_TOKEN \
          --data '{"event_type": "saucectl_release", "client_payload": { "version": "$(git describe --abbrev | cut -c2-)" }}'