# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: saucectl Pipline

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    container: golang:1.14-alpine
         
    steps:
      - name: Install Git
        run: sudo apt-get install git

      - name: Checkout Code
        uses: actions/checkout@v2
        
      - name: Install dependencies
        run: go get ./...
        
      - name: Build project
        run: go build cmd/saucectl/saucectl.go

      - name: Run tests
        run: |
          go test -coverprofile=coverage.out ./...
          goverreport -sort=block -order=desc -threshold=0